language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install codecov
  - pip install coveralls
  - pip install pytest pytest-cov

script:
  - pytest --cov=gostcrypto

after_success:
  - codecov
  - coveralls